name: Publish Packages

on: 
  push:
    branches: 
      - master
    tags:
      - "*"

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: set release version and set delete source code
        run: |
          echo ::set-env name=CI_COMMIT_TAG::${GITHUB_REF#refs/*/}
          echo ::set-env name=API_KEY::${{secrets.NUGET_API_KEY}}
      - uses: actions/checkout@v2

      # Publish
      - name: publish on version change
        run: |
          dotnet build -c Release chiao_test/chiao_test.csproj
