name: Publish Packages

on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/luckchiao/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - run: dotnet build chiao_test
    - name: Create the package
      run: dotnet pack --configuration Release chiao_test -p:PackageVersion=${GITHUB_REF#refs/*/} -o .
    - name: Publish the package to GPR
      run: dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
