name: Publish Packages

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set release version and set delete source code
        run: |
          echo ::set-env name=CI_COMMIT_TAG::${GITHUB_REF#refs/*/}
          echo ::set-env name=API_KEY::${{secrets.NUGET_API_KEY}}
      - name: complie
        run: cd chiao_test; dotnet restore; dotnet build --configuration Release --no-restore; dotnet pack -p:PackageVersion=${{ env.CI_COMMIT_TAG }}
      - name: push-nupkg
        run: dotnet nuget push chiao_test/bin/Debug/chiao_test.${{ env.CI_COMMIT_TAG }}.nupkg -k ${{ env.API_KEY }} -s https://api.nuget.org/v3/index.json
