name: Publish Packages

on: 
  push:
    branches: 
      - master
    tags:
      - "*"
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    env:
      working-directory: ./chiao_test/
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: chiao_test/chiao_test.csproj
          VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
